---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://karenksh.github.io/mysite-hugo"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
theme: "hugo_theme_robust"
...
