languageCode = "en-us"
baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "Try again. Fail again. Fail better."
disqusShortname = "disqus_karenx"
theme = "hugo_theme_robust"
MetaDataFormat = "yaml"
